### ISSUE TITLE
VerifyTaskExists possible raise condition

### ISSUE THREAD

**Issue by swaros** [swaros/contxt#178]
**Describe the bug**
checking needs can run in a panic
` panic: verify lock is already locked. Nested calls of 'VerifyTaskExists' are not allowed`

this is depending the rework of the watchman refactoring.
so nothing that could call an `VerifyTaskExists`, inside another `VerifyTaskExists` callback, is allowed and results in a Panic.

but it seems this is also the case because of raise conditions, so this have to be reworked.

**To Reproduce**
1. start interactive mode 
2. run targets they have nested needs
3. use command `taskreset`
4. re run the tasks

**Expected behavior**

**Screenshots**
![image](https://github.com/swaros/contxt/assets/5437750/da805769-e9c1-4cc2-a412-5cb56900c7d3)

**Comment by swaros** [comment]
the log 

```
goroutine 150 [running]:
github.com/swaros/contxt/module/tasks.(*Watchman).VerifyTaskExists(0xc000032280, {0xc001413770?, 0x1?}, 0xc0026018d8)
	/home/tziegler/develop/projects/playground/contxt/module/tasks/watchman.go:365 +0xc5
github.com/swaros/contxt/module/tasks.(*targetExecuter).executeTemplate(0xc001b001a0, 0x1, {0xc0014136b0, 0x12}, 0xc001b920c0)
	/home/tziegler/develop/projects/playground/contxt/module/tasks/execTemplate.go:289 +0x24f4
github.com/swaros/contxt/module/tasks.(*targetExecuter).generateFuturesByTargetListAndExec.func1({0x922d28?, 0xc001b92000?})
	/home/tziegler/develop/projects/playground/contxt/module/tasks/execTemplate.go:426 +0x16a
github.com/swaros/contxt/module/awaitgroup.FutureStack.Await({0xc00184df00?, {0x7ee360?, 0xc00184df10?}})
	/home/tziegler/develop/projects/playground/contxt/module/awaitgroup/await.go:69 +0x50
github.com/swaros/contxt/module/awaitgroup.ExecFuture.func1()
	/home/tziegler/develop/projects/playground/contxt/module/awaitgroup/await.go:78 +0x5d
created by github.com/swaros/contxt/module/awaitgroup.ExecFuture in goroutine 77
	/home/tziegler/develop/projects/playground/contxt/module/awaitgroup/await.go:76 +0xaa

```
